"""Criação da tabela Cliente

Revision ID: 2acfaade2f1c
Revises: 
Create Date: 2023-04-22 09:55:53.917546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acfaade2f1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id_cliente', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=9), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cliente')
    # ### end Alembic commands ###
