"""Criação da tabela Agendamento

Revision ID: a95bfc888f04
Revises: 2acfaade2f1c
Create Date: 2023-04-22 14:30:46.611577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95bfc888f04'
down_revision = '2acfaade2f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agendamento',
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=True),
    sa.Column('horario_fim', sa.DateTime(), nullable=True),
    sa.Column('id_cliente', sa.String(length=32), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['Cliente.id_cliente'], name=op.f('fk_4be51048-ebb1-50f1-a04b-2b8a59e5193b')),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Agendamento')
    # ### end Alembic commands ###
